parameters:
    tachigo_ui_bundle.template_root: %src_root%/Tachigo/Bundle/UI/Template

services:
    twig.filesystem_loader:
        calls:
            - [addPath, [%tachigo_ui_bundle.template_root%, TachigoUIModule]]